import type {
  AlertStatus,
  Difficulty,
  InvestigationStatus,
  RuleFormat,
  Severity,
} from "@cyberforge/types";
import { Badge, cn } from "@cyberforge/ui";
import { FlaskConical } from "lucide-react";
import Link from "next/link";

import {
  ALERT_STATUS_LABEL,
  INVESTIGATION_STATUS_LABEL,
  SEVERITY_LABEL,
  titleCase,
} from "@/lib/format";

const SEVERITY_VARIANT = {
  critical: "critical",
  high: "high",
  medium: "medium",
  low: "low",
  informational: "info",
} as const;

export function SeverityBadge({ severity, className }: { severity: Severity; className?: string }) {
  return (
    <Badge variant={SEVERITY_VARIANT[severity]} className={className} data-severity={severity}>
      <span aria-hidden className="size-1.5 rounded-full bg-current" />
      {SEVERITY_LABEL[severity]}
    </Badge>
  );
}

const STATUS_VARIANT = {
  new: "accent",
  investigating: "warning",
  contained: "outline",
  resolved: "success",
  false_positive: "neutral",
} as const;

export function AlertStatusBadge({ status }: { status: AlertStatus }) {
  return <Badge variant={STATUS_VARIANT[status]}>{ALERT_STATUS_LABEL[status]}</Badge>;
}

const INV_VARIANT = {
  open: "accent",
  in_progress: "warning",
  contained: "outline",
  closed: "success",
} as const;

export function InvestigationStatusBadge({ status }: { status: InvestigationStatus }) {
  return <Badge variant={INV_VARIANT[status]}>{INVESTIGATION_STATUS_LABEL[status]}</Badge>;
}

const DIFFICULTY_VARIANT = {
  beginner: "success",
  intermediate: "warning",
  advanced: "high",
} as const;

export function DifficultyBadge({ difficulty }: { difficulty: Difficulty }) {
  return <Badge variant={DIFFICULTY_VARIANT[difficulty]}>{titleCase(difficulty)}</Badge>;
}

export function FormatBadge({ format }: { format: RuleFormat }) {
  return (
    <Badge variant="outline" className="font-mono uppercase">
      {format}
    </Badge>
  );
}

export function SyntheticBadge({ className }: { className?: string }) {
  return (
    <Badge
      variant="outline"
      className={cn("gap-1", className)}
      title="Generated by CyberForge for training; not from a real system"
    >
      <FlaskConical className="size-3" />
      Synthetic
    </Badge>
  );
}

export function TechniqueChip({
  id,
  name,
  className,
}: {
  id: string;
  name?: string;
  className?: string;
}) {
  return (
    <Link
      href={`/mitre/${id}`}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md outline-none focus-visible:ring-2 focus-visible:ring-ring",
        className,
      )}
      title={name ? `${id} ${name}` : id}
    >
      <Badge
        variant="outline"
        className="font-mono transition-colors hover:border-primary/50 hover:text-primary"
      >
        {id}
      </Badge>
      {name ? <span className="truncate text-xs text-muted-foreground">{name}</span> : null}
    </Link>
  );
}
