"""Incident report rendering (Markdown / JSON). PDF is an extension point: see docs."""

from __future__ import annotations

from typing import Any

from cyberforge.models import IncidentReport, Investigation


def report_dict(inv: Investigation, report: IncidentReport) -> dict[str, Any]:
    return {
        "schema": "cyberforge.incident-report/v1",
        "investigation": {
            "id": inv.id,
            "title": inv.title,
            "severity": inv.severity,
            "status": inv.status,
            "lead": inv.lead.name if inv.lead else None,
            "created_at": inv.created_at.isoformat(),
            "synthetic": inv.synthetic,
        },
        "report": {
            "status": report.status,
            "executive_summary": report.executive_summary,
            "timeline": report.timeline,
            "affected_assets": report.affected_assets,
            "indicators": report.indicators,
            "mitre_techniques": report.mitre_techniques,
            "evidence": report.evidence,
            "root_cause": report.root_cause,
            "containment": report.containment,
            "remediation": report.remediation,
            "lessons_learned": report.lessons_learned,
            "updated_at": report.updated_at.isoformat(),
        },
        "alerts": [
            {
                "id": a.id,
                "title": a.title,
                "severity": a.severity,
                "technique": a.technique_id,
                "host": a.host,
            }
            for a in inv.alerts
        ],
    }


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "_None recorded._"


def _text(value: str) -> str:
    return value.strip() or "_Not provided._"


def to_markdown(inv: Investigation, report: IncidentReport) -> str:
    lines = [
        f"# Incident Report: {inv.title}",
        "",
        f"**Severity:** {inv.severity} · **Status:** {inv.status} · **Report:** {report.status}"
        + (f" · **Lead:** {inv.lead.name}" if inv.lead else ""),
    ]
    if inv.synthetic:
        lines += [
            "",
            "> Synthetic incident generated by CyberForge for training. Not a real event.",
        ]
    lines += [
        "",
        "## Executive Summary",
        "",
        _text(report.executive_summary),
        "",
        "## Incident Timeline",
        "",
    ]
    if report.timeline:
        lines += ["| Time (UTC) | Event |", "| --- | --- |"]
        lines += [
            f"| {row.get('time', '')} | {str(row.get('event', '')).replace('|', '/')} |"
            for row in report.timeline
        ]
    else:
        lines.append("_None recorded._")
    lines += [
        "", "## Affected Assets", "", _bullets(report.affected_assets),
        "", "## Indicators", "", _bullets([f"`{i}`" for i in report.indicators]),
        "", "## MITRE Techniques", "", _bullets(report.mitre_techniques),
        "", "## Evidence", "", _text(report.evidence),
        "", "## Root Cause", "", _text(report.root_cause),
        "", "## Containment", "", _text(report.containment),
        "", "## Remediation", "", _text(report.remediation),
        "", "## Lessons Learned", "", _text(report.lessons_learned),
        "", "---", f"_Exported from CyberForge · last updated {report.updated_at.isoformat()}_", "",
    ]  # fmt: skip
    return "\n".join(lines)
