#!/usr/bin/env python3
"""Write JSON Schema for every hand-authored content type to schemas/*.schema.json.

The Pydantic models in apps/api/cyberforge/content are the single source of truth; these files let
editors validate and autocomplete YAML (add `# yaml-language-server: $schema=...` to a file, or map
the schema in your editor settings). CI fails if the committed files are out of date:

    python scripts/export_schemas.py          # rewrite
    python scripts/export_schemas.py --check  # exit 1 if a schema is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "apps" / "api"))

from cyberforge.content.demos import DemoScenario
from cyberforge.content.schemas import (
    LabDoc,
    LabTestsDoc,
    PlaygroundDataset,
)
from cyberforge.content.stories import StoryDoc
from cyberforge.services.rule_tests import RuleTestFile

SCHEMAS = {
    "lab": (LabDoc, "labs/<domain>/<slug>/lab.yaml"),
    "lab-tests": (LabTestsDoc, "labs/<domain>/<slug>/tests/lab.tests.yml"),
    "rule-tests": (RuleTestFile, "detections/sigma/**/<slug>.tests.yml"),
    "story": (StoryDoc, "stories/<slug>.yaml"),
    "demo": (DemoScenario, "demos/<slug>.yaml"),
    "dataset": (PlaygroundDataset, "datasets/playground/<slug>.yaml"),
}


def render(model: type, describes: str) -> str:
    schema = model.model_json_schema()  # type: ignore[attr-defined]
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": f"Generated by scripts/export_schemas.py. Describes {describes}.",
        **schema,
    }
    return json.dumps(schema, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if committed schemas are stale")
    args = parser.parse_args()
    out = ROOT / "schemas"
    out.mkdir(exist_ok=True)
    stale = []
    for name, (model, describes) in SCHEMAS.items():
        path = out / f"{name}.schema.json"
        text = render(model, describes)
        if args.check:
            current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
            if current != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote schemas/{path.name}")
    if stale:
        print("stale schemas: " + ", ".join(stale) + "\nrun: pnpm schemas", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
