"""Repository statistics, calculated from the content on disk. Nothing here is hard-coded."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from cyberforge.content.loader import ContentBundle, load_bundle
from cyberforge.services import rule_quality, rule_tests


def collect(root: Path, bundle: ContentBundle | None = None) -> dict[str, Any]:
    bundle = bundle or load_bundle(root)
    summary = rule_tests.run_all(bundle)
    quality = rule_quality.evaluate_all(bundle, summary)
    by_format: dict[str, int] = {}
    for rule in bundle.rules:
        by_format[rule.format] = by_format.get(rule.format, 0) + 1
    mapped = {t for lab in bundle.labs for t in lab.doc.mitre} | {
        t for r in bundle.rules for t in r.technique_ids
    }
    story_techniques = {t for s in bundle.stories for t in s.techniques()}
    return {
        "labs": len(bundle.labs),
        "sigma_rules": by_format.get("sigma", 0),
        "yara_rules": by_format.get("yara", 0),
        "suricata_rules": by_format.get("suricata", 0),
        "mitre_techniques_mapped": len(mapped | story_techniques),
        "mitre_techniques_in_dataset": len(bundle.mitre_techniques),
        "stories": len(bundle.stories),
        "datasets": len(bundle.playground_datasets),
        "demos": len(bundle.demos),
        "learning_tracks": len(bundle.tracks),
        "incidents": len(bundle.incidents),
        "detection_tests": summary.test_count,
        "detection_test_coverage": {
            "rules": summary.rule_count,
            "tested": summary.tested_rules,
            "percent": summary.coverage_percent,
        },
        "quality_checks": {
            "passed": sum(q.passed for q in quality),
            "total": sum(q.total for q in quality),
        },
    }


def as_rows(data: dict[str, Any]) -> list[tuple[str, int | str]]:
    cov = data["detection_test_coverage"]
    return [
        ("Labs", data["labs"]),
        ("Sigma rules", data["sigma_rules"]),
        ("YARA rules", data["yara_rules"]),
        ("Suricata rules", data["suricata_rules"]),
        ("MITRE techniques mapped", data["mitre_techniques_mapped"]),
        ("Attack stories", data["stories"]),
        ("Detection datasets", data["datasets"]),
        ("Live demos", data["demos"]),
        ("Detection tests", data["detection_tests"]),
        ("Detection test coverage", f"{cov['tested']}/{cov['rules']} ({cov['percent']}%)"),
    ]


def as_markdown(data: dict[str, Any]) -> str:
    lines = ["| | |", "| --- | ---: |"]
    lines += [f"| {label} | {value} |" for label, value in as_rows(data)]
    return "\n".join(lines)


START = "<!-- stats:start -->"
END = "<!-- stats:end -->"


def render_block(data: dict[str, Any]) -> str:
    """The generated README block, markers included."""
    note = "<!-- Generated by `pnpm content:readme`. Do not edit by hand. -->"
    return "\n".join([START, note, "", as_markdown(data), "", END])


def update_readme(root: Path, *, check: bool = False) -> bool:
    """Rewrite the counts block in README.md from repository content.

    Returns True when the file is (or, with check=False, has been made) up to date.
    """
    path = root / "README.md"
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError(f"README.md needs a {START} ... {END} block")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + render_block(collect(root)) + tail
    if updated == text:
        return True
    if check:
        return False
    path.write_text(updated, encoding="utf-8", newline="\n")
    return True
